---
title: "angsd_association_RAD_per_pop"
author: "Anita Wray"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
start_time <- Sys.time()
knitr::opts_knit$set(root.dir ="~/Desktop/methow_steelhead/RADseq/angsd_analysis/")
library(tidyverse)
library(qqman)
library(RColorBrewer)
```

```{r read in files - LC - filtered, echo=FALSE}
library(tidyverse)

header <- c('Chromosome',	'Position',	'Major',	'Minor',	'Frequency',	'N',	'LRT',	'high_WT/HE/HO')

lrt_filt_LC <- read_tsv("asso-results_RAD_LC.txt", col_names = header)


new_chr_name <- read.delim("../chromosome_table.tsv", header = F, col.names = c("NCBI", "CHR_NUM"))
new_chr_name$CHR_NUM <- as.factor(new_chr_name$CHR_NUM)

lrt_filt_LC <- merge(lrt_filt_LC, new_chr_name, by.x = "Chromosome", by.y = "NCBI", all = TRUE)


#colnames(lrt) <- header
df_LC <- lrt_filt_LC %>% mutate(log10p = -log10(dchisq(LRT, df = 1))) %>%
  filter(log10p>=0 & log10p != "Inf") %>%
  mutate(p = dchisq(LRT, df=1)) %>%
  mutate(bonfer = p.adjust(p, method = "bonferroni")) %>% 
  mutate(BHfdr = p.adjust(p, method = "BH")) %>%
    group_by(Chromosome) %>%
    mutate(adjpchrom = p.adjust(p, method = "bonferroni")) %>%
    mutate(BHfdrchrom = p.adjust(p, method = "BH"))


(dfs_LC<- df_LC %>% arrange(-LRT) %>% head(n=20))


sig_snps <- df_LC %>% arrange(-LRT) %>% subset(log10p > -log10(0.05/nrow(df_LC)))
write.csv(sig_snps, file = "LC_RAD_sig_snps.csv")
```

```{r p-values & plotting - LC - filtered, echo=FALSE, fig.height=8}
color_group <- rep(c("lightgrey", "black"), length.out = 29)

(LC_plot <- ggplot(df_LC) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_LC)), col="black", linetype=2, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  scale_color_manual(values= color_group) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("LC") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  facet_wrap(.~CHR_NUM, ncol = 5, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())+
  ylim(0,10))

```


```{r read in files - LW - filtered, echo=FALSE}
library(tidyverse)

header <- c('Chromosome',	'Position',	'Major',	'Minor',	'Frequency',	'N',	'LRT',	'high_WT/HE/HO')

lrt_filt_LW <- read_tsv("asso-results_RAD_LW.txt", col_names = header)

new_chr_name <- read.delim("../chromosome_table.tsv", header = F, col.names = c("NCBI", "CHR_NUM"))
new_chr_name$CHR_NUM <- as.factor(new_chr_name$CHR_NUM)

lrt_filt_LW <- merge(lrt_filt_LW, new_chr_name, by.x = "Chromosome", by.y = "NCBI", all = TRUE)

#colnames(lrt) <- header
df_LW <- lrt_filt_LW %>% mutate(log10p = -log10(dchisq(LRT, df = 1))) %>%
  filter(log10p>=0 & log10p != "Inf") %>%
  mutate(p = dchisq(LRT, df=1)) %>%
  mutate(bonfer = p.adjust(p, method = "bonferroni")) %>% 
  mutate(BHfdr = p.adjust(p, method = "BH")) %>%
    group_by(Chromosome) %>%
    mutate(adjpchrom = p.adjust(p, method = "bonferroni")) %>%
    mutate(BHfdrchrom = p.adjust(p, method = "BH"))


(dfs_LW<- df_LW %>% arrange(-LRT) %>% head(n=20))

sig_snps <- df_LW %>% arrange(-LRT) %>% subset(log10p > -log10(0.05/nrow(df_LW)))
write.csv(sig_snps, file = "LW_RAD_sig_snps.csv")
```

```{r p-values & plotting - LW - filtered, echo=FALSE, fig.height=8}
color_group <- rep(c("lightgrey", "black"), length.out = 29)

(LW_plot <- ggplot(df_LW) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_LW)), col="black", linetype=2, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  scale_color_manual(values= color_group) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("LW") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  facet_wrap(.~CHR_NUM, ncol = 5, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())+
  ylim(0,10))

```



```{r read in files - EC - filtered, echo=FALSE}
library(tidyverse)

header <- c('Chromosome',	'Position',	'Major',	'Minor',	'Frequency',	'N',	'LRT',	'high_WT/HE/HO')

lrt_filt_EC <- read_tsv("asso-results_RAD_EC.txt", col_names = header)

new_chr_name <- read.delim("../chromosome_table.tsv", header = F, col.names = c("NCBI", "CHR_NUM"))
new_chr_name$CHR_NUM <- as.factor(new_chr_name$CHR_NUM)

lrt_filt_EC <- merge(lrt_filt_EC, new_chr_name, by.x = "Chromosome", by.y = "NCBI", all = TRUE)

#colnames(lrt) <- header
df_EC <- lrt_filt_EC %>% mutate(log10p = -log10(dchisq(LRT, df = 1))) %>%
  filter(log10p>=0 & log10p != "Inf") %>%
  mutate(p = dchisq(LRT, df=1)) %>%
  mutate(bonfer = p.adjust(p, method = "bonferroni")) %>% 
  mutate(BHfdr = p.adjust(p, method = "BH")) %>%
    group_by(Chromosome) %>%
    mutate(adjpchrom = p.adjust(p, method = "bonferroni")) %>%
    mutate(BHfdrchrom = p.adjust(p, method = "BH"))


(dfs_EC<- df_EC %>% arrange(-LRT) %>% head(n=20))

sig_snps <- df_EC %>% arrange(-LRT) %>% subset(log10p > -log10(0.05/nrow(df_EC)))
write.csv(sig_snps, file = "EC_RAD_sig_snps.csv")
```

```{r p-values & plotting - EC - filtered, echo=FALSE, fig.height=8}
color_group <- rep(c("lightgrey", "black"), length.out = 29)


(EC_plot <- ggplot(df_EC) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_EC)), col="black", linetype=2, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  scale_color_manual(values= color_group) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("EC") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  ylim(0,10) +
  facet_wrap(.~CHR_NUM, ncol = 5, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank()))

```



```{r read in files - EW - filtered, echo=FALSE}
library(tidyverse)

header <- c('Chromosome',	'Position',	'Major',	'Minor',	'Frequency',	'N',	'LRT',	'high_WT/HE/HO')

lrt_filt_EW <- read_tsv("asso-results_RAD_EW.txt", col_names = header)

new_chr_name <- read.delim("../chromosome_table.tsv", header = F, col.names = c("NCBI", "CHR_NUM"))
new_chr_name$CHR_NUM <- as.factor(new_chr_name$CHR_NUM)

lrt_filt_EW <- merge(lrt_filt_EW, new_chr_name, by.x = "Chromosome", by.y = "NCBI", all = TRUE)

#colnames(lrt) <- header
df_EW <- lrt_filt_EW %>% mutate(log10p = -log10(dchisq(LRT, df = 1))) %>%
  filter(log10p>=0 & log10p != "Inf") %>%
  mutate(p = dchisq(LRT, df=1)) %>%
  mutate(bonfer = p.adjust(p, method = "bonferroni")) %>% 
  mutate(BHfdr = p.adjust(p, method = "BH")) %>%
    group_by(Chromosome) %>%
    mutate(adjpchrom = p.adjust(p, method = "bonferroni")) %>%
    mutate(BHfdrchrom = p.adjust(p, method = "BH"))


(dfs_EW<- df_EW %>% arrange(-LRT) %>% head(n=20))

sig_snps <- df_EW %>% arrange(-LRT) %>% subset(log10p > -log10(0.05/nrow(df_EW)))
write.csv(sig_snps, file = "EW_RAD_sig_snps.csv")
```

```{r p-values & plotting - EW - filtered, echo=FALSE, fig.height=8}
color_group <- rep(c("lightgrey", "black"), length.out = 29)

(EW_plot <- ggplot(df_EW) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_EW)), col="black", linetype=2, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  scale_color_manual(values= color_group) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("EW") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  facet_wrap(.~CHR_NUM, ncol = 5, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())+
  ylim(0,10))

```


```{r echo=FALSE, fig.height=10, fig.width=14}
library(patchwork)

(EW_plot|EC_plot)/(LW_plot|LC_plot)

```

```{r fig.height=4, fig.width=12}

EW_plot_2 <- ggplot(df_EW) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_EW)), col="black", linetype=2, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  scale_color_manual(values= color_group) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("EW") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  facet_wrap(.~CHR_NUM, ncol = 29, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), 
        panel.spacing = unit(0, "cm"),
        panel.border = element_blank())+
  ylim(0,100)

EC_plot_2 <- ggplot(df_EC) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_EC)), col="black", linetype=2, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  scale_color_manual(values= color_group) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("EC") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  facet_wrap(.~CHR_NUM, ncol = 29, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), 
        panel.spacing = unit(0, "cm"),
        panel.border = element_blank())+
  ylim(0,105)

EW_plot_2/EC_plot_2
```


# Session Info

```{r sesh info, eval=FALSE, include=FALSE}
sessioninfo::session_info()
```

# Running Time

Running the code and rendering this notebook required approximately this much time
on a Mac laptop of middling speed:
```{r est time, echo=FALSE}
Sys.time() - start_time
```