---
title: "angsd_association_RAD_noPCs"
author: "Anita Wray"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
start_time <- Sys.time()
knitr::opts_knit$set(root.dir ="~/Desktop/methow_steelhead/RADseq/")
library(tidyverse)
library(qqman)
library(RColorBrewer)
```

```{r read in files - noPC - filtered, echo=FALSE}
library(tidyverse)

header <- c('Chromosome',	'Position',	'Major',	'Minor',	'Frequency',	'N',	'LRT',	'high_WT/HE/HO')

lrt_filt_noPC <- read_tsv("RAD_noPC_asso_results.txt", col_names = header)

#colnames(lrt) <- header
df_noPC <- lrt_filt_noPC %>% mutate(log10p = -log10(dchisq(LRT, df = 1))) %>%
  filter(log10p>=0 & log10p != "Inf") %>%
  mutate(p = dchisq(LRT, df=1)) %>%
  mutate(bonfer = p.adjust(p, method = "bonferroni")) %>% 
  mutate(BHfdr = p.adjust(p, method = "BH")) %>%
    group_by(Chromosome) %>%
    mutate(adjpchrom = p.adjust(p, method = "bonferroni")) %>%
    mutate(BHfdrchrom = p.adjust(p, method = "BH"))


dfs_noPC<- df_noPC %>% arrange(-LRT) %>% head(n=20)
```

```{r p-values & plotting - noPC - filtered, echo=FALSE, fig.height=8}
nb.cols <- length(unique(df_noPC$Chromosome))
mycolors <- colorRampPalette(brewer.pal(8, "Set1"))(nb.cols)
#randomize
mycolors<-sample(mycolors)


noPC_plot <- ggplot(df_noPC) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_noPC)), col="black", linetype=2, alpha=0.5) +
  geom_hline(yintercept= 4, col="black", linetype=1, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  #scale_color_manual(values=mycolors) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("0PCs") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  facet_wrap(.~Chromosome, ncol = 5, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

```

```{r read in files - 2PC - filtered}
header <- c('Chromosome',	'Position',	'Major',	'Minor',	'Frequency',	'N',	'LRT',	'high_WT/HE/HO')

lrt_filt_2PC <- read_tsv("twoPC_RAD_asso_results.txt", col_names = header)

#colnames(lrt_filt_2PC) <- header

#colnames(lrt) <- header
df_2PC <- lrt_filt_2PC %>% mutate(log10p = -log10(dchisq(LRT, df = 1))) %>%
  filter(log10p>=0 & log10p != "Inf") %>%
  mutate(p = dchisq(LRT, df=1)) %>%
  mutate(bonfer = p.adjust(p, method = "bonferroni")) %>% 
  mutate(BHfdr = p.adjust(p, method = "BH")) %>%
    group_by(Chromosome) %>%
    mutate(adjpchrom = p.adjust(p, method = "bonferroni")) %>%
    mutate(BHfdrchrom = p.adjust(p, method = "BH"))


dfs_2PC <- df_2PC %>% arrange(-LRT) %>% head(n=20)
```

```{r p-values & plotting - 2PC - filtered, echo=FALSE, fig.height=8}
nb.cols <- length(unique(df_2PC$Chromosome))
mycolors <- colorRampPalette(brewer.pal(8, "Set1"))(nb.cols)
#randomize
mycolors<-sample(mycolors)


twoPC_plot <- ggplot(df_2PC) +
  geom_point(aes(x=Position, y=log10p, color=Chromosome), alpha=0.75, cex=0.5) +
  geom_hline(yintercept = -log10(0.05/nrow(df_2PC)), col="black", linetype=2, alpha=0.5) +
  geom_hline(yintercept= 4, col="black", linetype=1, alpha=0.5) +
  theme_bw() +
  #scale_x_continuous(breaks=chroms$Position, labels=chroms$Chromosome) +
  theme(axis.text.x = element_text(angle=45, hjust = 1, face="bold", size=8)) +
  theme(legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  #scale_color_manual(values=mycolors) +
  ylab("-log10(p)\n") +
  xlab("\nChromosome") +
  ggtitle("2PCs") +
  theme(plot.title = element_text(hjust=0.5) ) +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  facet_wrap(.~Chromosome, ncol = 5, scales="free_x") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
```

```{r fig.height=10, fig.width=10}
library(patchwork)

twoPC_plot|noPC_plot
```



# Session Info

```{r sesh info, eval=FALSE, include=FALSE}
sessioninfo::session_info()
```

# Running Time

Running the code and rendering this notebook required approximately this much time
on a Mac laptop of middling speed:
```{r est time, echo=FALSE}
Sys.time() - start_time
```