#!/bin/bash
#SBATCH --job-name=clone_fiter_06
#SBATCH --output=../../logs/clone_filter.06.%A.%a.log
#SBATCH -t 400:00:00
#SBATCH --array=1-96
#SBATCH -c 1
#SBATCH -p medmem
#SBATCH -D /scratch2/mkardos/methowRAD/results/indsamps/06

case $SLURM_ARRAY_TASK_ID in
1) IN=GGACAAGCTA ;;
2) IN=GGAACAACCA ;;
3) IN=GGAGATCGCA ;;
4) IN=GGCCGAAGTA ;;
5) IN=GGGATAGACA ;;
6) IN=GGTATCAGCA ;;
7) IN=GGAATGTTGC ;;
8) IN=GGCCATCCTC ;;
9) IN=GGAAACATCG ;;
10) IN=GGAACCGAGA ;;
11) IN=GGAGCAGGAA ;;
12) IN=GGCCGTGAGA ;;
13) IN=GGGCCACATA ;;
14) IN=GGTCCGTCTA ;;
15) IN=GGACACTGAC ;;
16) IN=GGCCGACAAC ;;
17) IN=GGACATTGGC ;;
18) IN=GGAACGCTTA ;;
19) IN=GGAGTCACTA ;;
20) IN=GGCCTCCTGA ;;
21) IN=GGGCGAGTAA ;;
22) IN=GGTCTTCACA ;;
23) IN=GGACAGATTC ;;
24) IN=GGAGTCAAGC ;;
25) IN=GGACCACTGT ;;
26) IN=GGAAGACGGA ;;
27) IN=GGATCCTGTA ;;
28) IN=GGCGAACTTA ;;
29) IN=GGGCTAACGA ;;
30) IN=GGTGAAGAGA ;;
31) IN=GGAGATGTAC ;;
32) IN=GGCCTCTATC ;;
33) IN=GGAACGTGAT ;;
34) IN=GGAAGGTACA ;;
35) IN=GGATTGAGGA ;;
36) IN=GGCGACTGGA ;;
37) IN=GGGCTCGGTA ;;
38) IN=GGTGGAACAA ;;
39) IN=GGAGCACCTC ;;
40) IN=GGCGACACAC ;;
41) IN=GGCGCTGATC ;;
42) IN=GGACACAGAA ;;
43) IN=GGCAACCACA ;;
44) IN=GGCGCATACA ;;
45) IN=GGGGAGAACA ;;
46) IN=GGTGGCTTCA ;;
47) IN=GGAGCCATGC ;;
48) IN=GGCGGATTGC ;;
49) IN=GGCAGATCTG ;;
50) IN=GGACAGCAGA ;;
51) IN=GGCAAGACTA ;;
52) IN=GGCTCAATGA ;;
53) IN=GGGGTGCGAA ;;
54) IN=GGTGGTGGTA ;;
55) IN=GGAGGCTAAC ;;
56) IN=GGCTAAGGTC ;;
57) IN=GGATGCCTAA ;;
58) IN=GGACCTCCAA ;;
59) IN=GGCAATGGAA ;;
60) IN=GGCTGAGCCA ;;
61) IN=GGGTACGCAA ;;
62) IN=GGTTCACGCA ;;
63) IN=GGATAGCGAC ;;
64) IN=GGGAACAGGC ;;
65) IN=GGAACGAACG ;;
66) IN=GGACGCTCGA ;;
67) IN=GGCACTTCGA ;;
68) IN=GGCTGGCATA ;;
69) IN=GGGTCGTAGA ;;
70) IN=GGACACGAGA ;;
71) IN=GGACGACAAG ;;
72) IN=GGGACAGTGC ;;
73) IN=GGAGTACAAG ;;
74) IN=GGACGTATCA ;;
75) IN=GGCAGCGTTA ;;
76) IN=GGGAATCTGA ;;
77) IN=GGGTCTGTCA ;;
78) IN=GGAAGAGATC ;;
79) IN=GGATTGGCTC ;;
80) IN=GGGAGTTAGC ;;
81) IN=GGCATCAAGT ;;
82) IN=GGACTATGCA ;;
83) IN=GGCATACCAA ;;
84) IN=GGGACTAGTA ;;
85) IN=GGGTGTTCTA ;;
86) IN=GGAAGGACAC ;;
87) IN=GGCAAGGAGC ;;
88) IN=GGGATGAATC ;;
89) IN=GGAGTGGTCA ;;
90) IN=GGAGAGTCAA ;;
91) IN=GGCCAGTTCA ;;
92) IN=GGGAGCTGAA ;;
93) IN=GGTAGGATGA ;;
94) IN=GGAATCCGTC ;;
95) IN=GGCACCTTAC ;;
96) IN=GGGCCAAGAC ;;
esac

module load bio/stacks/2.62
clone_filter -1 sample_${IN}.1.fq.gz -2 sample_${IN}.2.fq.gz -i gzfastq -o ../../clone_filtered/06/ > ../../logs/clone_filter.06.${IN}.log



